//! Scheduled Research — AI subscription execution engine (#2167).
//!
//! Runs AI subscription tasks: executes the prompt, saves the result
//! as a vault note in the target collection, and updates run metadata.

use std::time::Duration;

use anyhow::Result;
use tracing::instrument;

use crate::models::{AiSubscription, NoteDocument, NoteMeta};
use crate::storage::{
    save_note_with_context, StorageContext,
};
use crate::storage::subscriptions::{
    list_due_subscriptions_with_context,
    update_subscription_run_with_context,
};

/// Per-subscription AI call timeout (3 minutes).
const _SUBSCRIPTION_AI_TIMEOUT: Duration = Duration::from_secs(180);
/// Timeout for storage-layer I/O.
const _STORAGE_IO_TIMEOUT: Duration = Duration::from_secs(30);

/// Run all due subscriptions (enabled subscriptions).
///
/// For each subscription:
/// 1. Execute the prompt via AI (ask_with_ai_with_context)
/// 2. Save the AI response as a note in the target collection
/// 3. Update subscription run metadata
#[instrument(skip(context))]
pub async fn run_all_due_subscriptions(
    context: &StorageContext,
) -> Vec<SubscriptionRunResult> {
    let subs = match list_due_subscriptions_with_context(context) {
        Ok(s) => s,
        Err(e) => {
            tracing::error!("failed to list due subscriptions: {e}");
            return vec![];
        }
    };

    if subs.is_empty() {
        tracing::info!("no due subscriptions to run");
        return vec![];
    }

    let mut results = Vec::with_capacity(subs.len());
    for sub in subs {
        tracing::info!(name = %sub.name, id = %sub.id, "running subscription");
        let result = run_single_subscription(context, &sub).await;
        results.push(result);
    }
    results
}

/// Result of a single subscription run.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionRunResult {
    pub subscription_id: String,
    pub subscription_name: String,
    pub status: String,
    pub note_id: Option<String>,
    pub note_title: Option<String>,
    pub error: Option<String>,
}

/// Execute a single subscription: prompt AI, save result as note.
#[instrument(skip(context, subscription))]
pub async fn run_single_subscription(
    context: &StorageContext,
    subscription: &AiSubscription,
) -> SubscriptionRunResult {
    let id = subscription.id.clone();
    let name = subscription.name.clone();

    // Step 1: Run the prompt via AI
    let prompt = &subscription.prompt;
    let tools = &subscription.tools;

    let result = execute_subscription_prompt(context, prompt, tools).await;

    let (status, note_id, note_title, error_msg) = match result {
        Ok(answer) => {
            // Step 2: Save the result as a vault note
            let title = format!(
                "[Scheduled] {} — {}",
                name,
                chrono::Utc::now().format("%Y-%m-%d %H:%M")
            );

            let meta = NoteMeta {
                title: title.clone(),
                summary: answer.chars().take(300).collect::<String>(),
                source: "ai_subscription".to_string(),
                tags: vec!["scheduled".to_string(), "ai".to_string()],
                ..Default::default()
            };

            let note = NoteDocument {
                meta,
                body: format!(
                    "# {}\n\n{}\n\n---\n*Generated by AI Scheduled Research*\n*Subscription: {}*\n*Prompt: {}*",
                    title, answer, name, prompt
                ),
                search_snippet: None,
            };

            match save_note_with_context(context, note) {
                Ok(saved_doc) => {
                    // Step 3: Update subscription run metadata
                    let _ = update_subscription_run_with_context(
                        context,
                        &id,
                        "success",
                        "",
                    );
                    ("success".to_string(), Some(saved_doc.meta.id.clone()), Some(saved_doc.meta.title.clone()), None)
                }
                Err(e) => {
                    let err = format!("failed to save note: {e}");
                    tracing::error!(id = %id, error = %err, "subscription save failed");
                    let _ = update_subscription_run_with_context(
                        context,
                        &id,
                        "failed",
                        &err,
                    );
                    ("failed".to_string(), None, None, Some(err))
                }
            }
        }
        Err(e) => {
            let err = format!("{e:#}");
            tracing::error!(id = %id, error = %err, "subscription execution failed");
            let _ = update_subscription_run_with_context(
                context,
                &id,
                "failed",
                &err,
            );
            ("failed".to_string(), None, None, Some(err))
        }
    };

    SubscriptionRunResult {
        subscription_id: id,
        subscription_name: name,
        status,
        note_id,
        note_title,
        error: error_msg,
    }
}

/// Execute the AI prompt for a subscription.
///
/// Uses ask_with_ai_with_context for rich grounding with vault context.
/// For tool-allowed subscriptions, we inject the available tools info.
async fn execute_subscription_prompt(
    context: &StorageContext,
    prompt: &str,
    _tools: &str,
) -> Result<String, anyhow::Error> {
    // Build a system-like instruction that wraps the subscription prompt.
    let effective_prompt = format!(
        r#"[Scheduled Research Task]
You are running a recurring research subscription.
Execute the following prompt thoroughly and provide a well-structured response.

RESEARCH PROMPT:
{}

Please provide a comprehensive response with:
- Key findings
- Sources/references where applicable
- Timestamp of this research
"#,
        prompt
    );

    // Use the existing ask API for grounded answers
    let answer = crate::ask_with_ai_with_context(
        context,
        effective_prompt,
        None,   // no history
        None,   // no images
        None,   // no model override
        |_, _| {}, // suppress status events
    )
    .await?;

    Ok(answer.answer)
}

// ─── Tests ────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::{
        initialize_storage_with_context, subscriptions::create_subscription_with_context,
        StorageContext,
    };
    use chrono::Utc;
    use std::path::PathBuf;

    fn setup_temp_context() -> (PathBuf, StorageContext) {
        let temp = std::env::temp_dir().join(format!(
            "vaultpilot-test-sr-{}",
            Utc::now().timestamp_nanos_opt().unwrap_or_default()
        ));
        std::fs::create_dir_all(&temp).expect("temp dir");
        let ctx = StorageContext::for_test(&temp);
        (temp, ctx)
    }

    #[test]
    fn test_run_subscription_updates_metadata() {
        let (_temp, ctx) = setup_temp_context();
        initialize_storage_with_context(&ctx).unwrap();

        // Create a subscription
        let sub = create_subscription_with_context(
            &ctx,
            "Test Run",
            "0 0 * * *",
            "test prompt that will fail without AI config",
            "web_search",
            "Test Collection",
        )
        .unwrap();

        // Run it — without valid AI config, it will fail, but metadata should update
        let result = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(run_single_subscription(&ctx, &sub));

        assert_eq!(result.subscription_id, sub.id);
        assert_eq!(result.subscription_name, "Test Run");
        // Without AI configured, it should fail gracefully
        assert_eq!(result.status, "failed");
        assert!(result.error.is_some());

        // Verify metadata was updated
        let updated = crate::storage::subscriptions::get_subscription_with_context(
            &ctx,
            &sub.id,
        )
        .unwrap()
        .unwrap();
        assert_eq!(updated.run_count, 1);
        assert_eq!(updated.last_status, "failed");
        assert!(!updated.last_error.is_empty());
    }

    #[test]
    fn test_run_all_due_empty() {
        let (_temp, ctx) = setup_temp_context();
        initialize_storage_with_context(&ctx).unwrap();

        let results = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(run_all_due_subscriptions(&ctx));
        assert!(results.is_empty());
    }

    #[test]
    fn test_run_all_due_skips_disabled() {
        let (_temp, ctx) = setup_temp_context();
        initialize_storage_with_context(&ctx).unwrap();

        // Create a disabled subscription
        let sub = create_subscription_with_context(
            &ctx,
            "Disabled Test",
            "0 0 * * *",
            "test",
            "",
            "",
        )
        .unwrap();
        crate::storage::subscriptions::set_subscription_enabled_with_context(
            &ctx,
            &sub.id,
            false,
        )
        .unwrap();

        let results = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(run_all_due_subscriptions(&ctx));
        // Disabled subscriptions are not returned by list_due
        assert!(results.is_empty());
    }
}
