using System.Text.Json.Serialization;

namespace VaultPilot.WinUI.Models;

public sealed record ChatAttachment
{
    public string Path { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;

    [JsonConstructor]
    public ChatAttachment() { }

    public ChatAttachment(string Path, string Name)
    {
        this.Path = Path ?? string.Empty;
        this.Name = Name ?? string.Empty;
    }
}

public sealed record ConversationTurn
{
    public string Role { get; init; } = string.Empty;
    public string Text { get; init; } = string.Empty;

    [JsonConstructor]
    public ConversationTurn() { }

    public ConversationTurn(string Role, string Text)
    {
        this.Role = Role ?? string.Empty;
        this.Text = Text ?? string.Empty;
    }
}

public sealed record ChatTurn
{
    public string Id { get; init; } = string.Empty;
    public string Role { get; init; } = string.Empty;
    public string Text { get; init; } = string.Empty;
    public IReadOnlyList<AnswerCitation>? Citations { get; init; }
    public NoteMeta? SavedNote { get; init; }
    public ThinkingTrace? ThinkingTrace { get; init; }
    public IReadOnlyList<ChatAttachment>? Attachments { get; init; }
    public string? CreatedAt { get; init; }
    /// <summary>
    /// Indicates the origin of this turn. Empty for normal (manual) messages;
    /// "scheduled_wake" for turns generated by the auto-wake timer (#861).
    /// </summary>
    public string Source { get; init; } = string.Empty;

    [JsonConstructor]
    public ChatTurn() { }

    public ChatTurn(
        string Id,
        string Role,
        string Text,
        IReadOnlyList<AnswerCitation>? Citations,
        NoteMeta? SavedNote,
        ThinkingTrace? ThinkingTrace,
        IReadOnlyList<ChatAttachment>? Attachments,
        string? CreatedAt,
        string? Source = null)
    {
        this.Id = Id ?? string.Empty;
        this.Role = Role ?? string.Empty;
        this.Text = Text ?? string.Empty;
        this.Citations = Citations;
        this.SavedNote = SavedNote;
        this.ThinkingTrace = ThinkingTrace;
        this.Attachments = Attachments;
        this.CreatedAt = CreatedAt;
        this.Source = Source ?? string.Empty;
    }
}

public sealed record ConversationSummary
{
    public string Text { get; init; } = string.Empty;
    public string GeneratedAt { get; init; } = string.Empty;
    public ulong CoveredTurnCount { get; init; }
    public ulong CompressionCount { get; init; }

    [JsonConstructor]
    public ConversationSummary() { }

    public ConversationSummary(string Text, string GeneratedAt, ulong CoveredTurnCount, ulong CompressionCount)
    {
        this.Text = Text ?? string.Empty;
        this.GeneratedAt = GeneratedAt ?? string.Empty;
        this.CoveredTurnCount = CoveredTurnCount;
        this.CompressionCount = CompressionCount;
    }
}

public sealed record ChatSession
{
    public string Id { get; init; } = string.Empty;
    public string Title { get; init; } = string.Empty;
    public IReadOnlyList<ChatTurn> Turns { get; init; } = Array.Empty<ChatTurn>();
    public ConversationSummary? Summary { get; init; }
    public string CreatedAt { get; init; } = string.Empty;
    public string UpdatedAt { get; init; } = string.Empty;

    [JsonConstructor]
    public ChatSession() { }

    /// <summary>
    /// Positional constructor for backward compatibility with existing code.
    /// </summary>
    public ChatSession(
        string Id,
        string Title,
        IReadOnlyList<ChatTurn> Turns,
        ConversationSummary? Summary,
        string CreatedAt,
        string UpdatedAt)
    {
        this.Id = Id ?? string.Empty;
        this.Title = Title ?? string.Empty;
        this.Turns = Turns ?? Array.Empty<ChatTurn>();
        this.Summary = Summary;
        this.CreatedAt = CreatedAt ?? string.Empty;
        this.UpdatedAt = UpdatedAt ?? string.Empty;
    }
}

public sealed record ChatState
{
    public string CurrentSessionId { get; init; } = string.Empty;
    public IReadOnlyList<ChatSession> Sessions { get; init; } = Array.Empty<ChatSession>();

    [JsonConstructor]
    public ChatState() { }

    /// <summary>
    /// Positional constructor for backward compatibility with existing code.
    /// </summary>
    public ChatState(
        string CurrentSessionId,
        IReadOnlyList<ChatSession> Sessions)
    {
        this.CurrentSessionId = CurrentSessionId ?? string.Empty;
        this.Sessions = Sessions ?? Array.Empty<ChatSession>();
    }
}

// ── MessageV2 — Unified cross-platform schema (#1239) ─────────────────

/// <summary>
/// Role of the message author.  Matches the Rust <c>MessageV2Role</c> enum.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MessageV2Role
{
    User,
    Assistant,
    System,
}

/// <summary>
/// Attachment type discriminator.  Matches the Rust <c>MessageV2AttachmentType</c> enum.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MessageV2AttachmentType
{
    Image,
    File,
}

/// <summary>
/// An attachment referenced by a MessageV2 message.
/// <c>Url</c> must use the <c>local://</c> scheme to prevent path-traversal attacks.
/// </summary>
public sealed record MessageV2Attachment
{
    [JsonPropertyName("type")]
    public MessageV2AttachmentType Type { get; init; } = MessageV2AttachmentType.File;

    public string Url { get; init; } = string.Empty;
    public string Mime { get; init; } = string.Empty;

    [JsonConstructor]
    public MessageV2Attachment() { }

    /// <summary>
    /// Returns <c>null</c> if the URL uses the <c>local://</c> scheme; otherwise an error message.
    /// </summary>
    public string? ValidateUrl()
    {
        if (!Url.StartsWith("local://", StringComparison.Ordinal))
            return $"attachment url must use local:// scheme, got: {Url}";
        return null;
    }
}

/// <summary>
/// Provider and token metadata attached to a MessageV2 message.
/// </summary>
public sealed record MessageV2Metadata
{
    public string Model { get; init; } = string.Empty;
    public ulong Tokens { get; init; }

    [JsonExtensionData]
    public Dictionary<string, System.Text.Json.JsonElement>? Extra { get; init; }

    [JsonConstructor]
    public MessageV2Metadata() { }
}

/// <summary>
/// Unified cross-platform message schema.
/// This is the canonical wire format shared by Rust, WinUI, and Mobile.
/// See issue #1239 for the full specification.
/// </summary>
public sealed record MessageV2
{
    public string Id { get; init; } = string.Empty;
    public MessageV2Role Role { get; init; } = MessageV2Role.User;
    public string Content { get; init; } = string.Empty;
    public IReadOnlyList<MessageV2Attachment> Attachments { get; init; } = Array.Empty<MessageV2Attachment>();
    public MessageV2Metadata Metadata { get; init; } = new();
    public Dictionary<string, System.Text.Json.JsonElement> Extensions { get; init; } = new();

    [JsonConstructor]
    public MessageV2() { }

    /// <summary>
    /// Full structural validation: checks attachment URLs.
    /// </summary>
    public IReadOnlyList<string> Validate()
    {
        var errors = new List<string>();
        foreach (var att in Attachments)
        {
            var err = att.ValidateUrl();
            if (err != null) errors.Add(err);
        }
        return errors;
    }
}
