//! Mermaid Code Block Extraction — detect and classify ```mermaid fenced
//! blocks inside Markdown note bodies (#3683).
//!
//! VaultPilot's three front-ends (WinUI, Mobile, CLI) all need to identify
//! mermaid diagram blocks so they can hand the source to a renderer
//! (WebView2 / react-native-webview / mermaid-cli).  This module provides the
//! shared backend logic:
//!
//! - [`extract_mermaid_blocks`] — scan Markdown and return every
//!   ```mermaid fenced block as a [`MermaidBlock`].
//! - [`MermaidBlock`] — the raw source, line range, and detected diagram type.
//! - [`MermaidDiagramType`] — best-effort classification (flowchart, sequence,
//!   gantt, …) so the UI can show an icon / choose a render strategy.
//!
//! ## Design notes
//!
//! - The parser is a lightweight line scanner — it does **not** depend on a
//!   full Markdown AST.  This keeps it fast for the common "does this note
//!   contain diagrams?" check and avoids pulling in a pulldown-cmark
//!   dependency just for this.
//! - Only fenced code blocks using three (or more) back-ticks with the info
//!   string `mermaid` are recognised, matching CommonMark / GFM semantics.
//! - Indented code blocks (4-space) are deliberately **not** treated as
//!   mermaid — they cannot carry an info string.
//! - Nested fences (a ``` block inside a ~~~ block or vice-versa) are handled
//!   by tracking the exact fence string that opened the block.
//! - A ` ```mermaid ` fence that appears *inside* another (non-mermaid)
//!   fenced code block — e.g. a 4-backtick documentation block or a `~~~`
//!   block — is correctly treated as literal text and **not** extracted
//!   (CommonMark: a fence with fewer back-ticks cannot close a wider one).
//!   See `test_mermaid_inside_wider_code_fence` and
//!   `test_mermaid_inside_tilde_fence` (#3726).

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// Known Mermaid diagram top-level keywords.
///
/// This is a best-effort classification based on the first non-comment,
/// non-directive line of the diagram source.  Unknown / custom diagram types
/// fall back to [`MermaidDiagramType::Unknown`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum MermaidDiagramType {
    /// `graph` / `flowchart` — the most common diagram type.
    #[default]
    Flowchart,
    /// `sequenceDiagram`
    Sequence,
    /// `classDiagram` / `classDiagram-v2`
    Class,
    /// `stateDiagram` / `stateDiagram-v2`
    State,
    /// `erDiagram` (entity-relationship)
    Er,
    /// `gantt`
    Gantt,
    /// `pie`
    Pie,
    /// `journey`
    Journey,
    /// `gitGraph`
    GitGraph,
    /// `mindmap` (also generated by VaultPilot's own mindmap module)
    Mindmap,
    /// `timeline`
    Timeline,
    /// `quadrantChart`
    Quadrant,
    /// `requirementDiagram`
    Requirement,
    /// `C4Context` / `C4Container` / `C4Component` (C4 model)
    C4,
    /// Anything we don't recognise yet.
    Unknown,
}

/// A mermaid code block extracted from a Markdown note.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MermaidBlock {
    /// The raw mermaid source **without** the surrounding fence lines.
    pub source: String,
    /// 1-based line number of the opening fence (the ``` line).
    pub start_line: usize,
    /// 1-based line number of the closing fence.
    pub end_line: usize,
    /// Best-effort diagram classification.
    pub diagram_type: MermaidDiagramType,
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Extract all ```mermaid fenced code blocks from a Markdown string.
///
/// Returns blocks in document order.  Each block's `source` is the raw text
/// between the fences (lines joined with `\n`, no trailing newline).
///
/// ```
/// use vaultpilot_lib::mermaid::{extract_mermaid_blocks, MermaidDiagramType};
///
/// // Build markdown with backtick fences via concat to avoid clashing with
/// // this doctest's own ``` fence.
/// let fence = concat!("#", "#", "```", "#"); // → ##```# (unused, placeholder)
/// let md = "Some text.\n\n".to_string()
///     + "```mermaid\ngraph TD\n  A --> B\n```\n\n"
///     + "More text.\n";
/// let blocks = extract_mermaid_blocks(&md);
/// assert_eq!(blocks.len(), 1);
/// assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Flowchart);
/// assert!(blocks[0].source.contains("A --> B"));
/// ```
pub fn extract_mermaid_blocks(markdown: &str) -> Vec<MermaidBlock> {
    let lines: Vec<&str> = markdown.lines().collect();
    let mut blocks = Vec::new();

    // Track any currently-active NON-mermaid fenced code block so that a
    // ` ```mermaid ` fence appearing *inside* it (as literal documentation
    // text) is not falsely extracted (#3726).  CommonMark: a fence with fewer
    // back-ticks cannot close a wider one, so the inner fence is just text.
    // Fields: (fence_char, fence_len).
    let mut active_fence: Option<(char, usize)> = None;

    let mut i = 0;
    while i < lines.len() {
        // If we are inside a non-mermaid code fence, scan forward until we
        // find its matching closing fence.
        if let Some((fence_char, fence_len)) = active_fence {
            if is_closing_fence_for(lines[i], fence_char, fence_len) {
                active_fence = None;
            }
            i += 1;
            continue;
        }
        if let Some(fence_len) = mermaid_fence_len(lines[i]) {
            // Found an opening ```mermaid fence at line `i` (0-based).
            let start_line = i + 1; // 1-based
            let mut source_lines: Vec<&str> = Vec::new();
            let mut closed = false;
            let mut j = i + 1;
            while j < lines.len() {
                if is_closing_fence(lines[j], fence_len) {
                    closed = true;
                    break;
                }
                source_lines.push(lines[j]);
                j += 1;
            }
            if closed {
                let end_line = j + 1; // 1-based
                let source = source_lines.join("\n");
                let diagram_type = classify_diagram(&source);
                blocks.push(MermaidBlock {
                    source,
                    start_line,
                    end_line,
                    diagram_type,
                });
                i = j + 1;
            } else {
                // Unterminated fence — consume the rest but skip it.
                break;
            }
        } else if let Some((fence_char, fence_len, _info)) = detect_fence(lines[i]) {
            // Opens a non-mermaid code block (``` / ~~~ / 4+ back-ticks).
            // Track it so subsequent lines are treated as literal until it
            // closes.  (mermaid_fence_len already handled the mermaid case.)
            active_fence = Some((fence_char, fence_len));
            i += 1;
        } else {
            i += 1;
        }
    }
    blocks
}

/// Check whether a Markdown note contains any mermaid blocks.
///
/// This is a cheap predicate that short-circuits on the first match — useful
/// for UI code that wants to decide whether to load the mermaid renderer at
/// all.  Like [`extract_mermaid_blocks`], it correctly skips ` ```mermaid `
/// fences that appear inside another (non-mermaid) code fence (#3726).
pub fn has_mermaid_blocks(markdown: &str) -> bool {
    let mut active_fence: Option<(char, usize)> = None;
    for line in markdown.lines() {
        if let Some((fence_char, fence_len)) = active_fence {
            if is_closing_fence_for(line, fence_char, fence_len) {
                active_fence = None;
            }
            continue;
        }
        if mermaid_fence_len(line).is_some() {
            return true;
        }
        if let Some((fence_char, fence_len, _info)) = detect_fence(line) {
            active_fence = Some((fence_char, fence_len));
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// If `line` is an opening fence for a mermaid block, return the number of
/// back-ticks used (≥ 3).  Otherwise return `None`.
///
/// Recognised forms:
/// - `` ```mermaid ``
/// - `` ````mermaid `` (4+ back-ticks)
/// - `` ```mermaid {args} `` (trailing info, ignored)
fn mermaid_fence_len(line: &str) -> Option<usize> {
    let trimmed = line.trim_start();
    let count = trimmed.chars().take_while(|&c| c == '`').count();
    if count < 3 {
        return None;
    }
    let after = &trimmed[count..];
    // The info string must start with "mermaid" as a word.
    let after_trimmed = after.trim_start();
    if after_trimmed.len() >= 7 && after_trimmed[..7].eq_ignore_ascii_case("mermaid") {
        // Ensure "mermaid" is not a prefix of a longer word (e.g. "mermaidfoo").
        let next = after_trimmed.as_bytes().get(7);
        match next {
            None => Some(count),
            Some(b) if b.is_ascii_whitespace() => Some(count),
            _ => None,
        }
    } else {
        None
    }
}

/// Detect *any* fenced code block opening (back-tick or tilde, ≥ 3 chars).
///
/// Returns the fence character, its length, and the trailing info string
/// (trimmed) when `line` opens a code fence.  Used to track non-mermaid code
/// blocks so that a ` ```mermaid ` fence nested inside them is treated as
/// literal text (#3726).
fn detect_fence(line: &str) -> Option<(char, usize, &str)> {
    let trimmed = line.trim_start();
    let first = trimmed.chars().next()?;
    if first != '`' && first != '~' {
        return None;
    }
    let count = trimmed.chars().take_while(|&c| c == first).count();
    if count < 3 {
        return None;
    }
    let info = trimmed[count..].trim();
    Some((first, count, info))
}

/// Check whether `line` is a closing fence with at least `min_len` back-ticks
/// (matching CommonMark's rule that the closing fence must be ≥ the opening
/// fence length).
fn is_closing_fence(line: &str, min_len: usize) -> bool {
    is_closing_fence_for(line, '`', min_len)
}

/// Check whether `line` closes the fence opened by `fence_char` with at least
/// `min_len` of the same character (CommonMark closing-fence rules: same char,
/// ≥ opening length, and nothing but whitespace after the fence markers).
fn is_closing_fence_for(line: &str, fence_char: char, min_len: usize) -> bool {
    let trimmed = line.trim_start();
    let count = trimmed.chars().take_while(|&c| c == fence_char).count();
    count >= min_len && count >= 3 && trimmed[count..].trim().is_empty()
}

/// Best-effort classification of a mermaid diagram from its source.
///
/// Mermaid determines the diagram type from the first meaningful directive
/// line.  We scan for the first non-blank, non-comment line and match its
/// leading keyword.
fn classify_diagram(source: &str) -> MermaidDiagramType {
    for line in source.lines() {
        let stripped = line.trim();
        if stripped.is_empty() {
            continue;
        }
        // Skip mermaid comments: `%% ...` or `%%{ ... }%%` directive prologues.
        if stripped.starts_with("%%") {
            continue;
        }
        // Match the keyword case-insensitively.
        let lower = stripped.to_ascii_lowercase();
        return match lower.as_str() {
            s if s.starts_with("graph ") || s.starts_with("flowchart ") => {
                MermaidDiagramType::Flowchart
            }
            s if s.starts_with("sequencediagram") => MermaidDiagramType::Sequence,
            s if s.starts_with("classdiagram") => MermaidDiagramType::Class,
            s if s.starts_with("statediagram") => MermaidDiagramType::State,
            s if s.starts_with("erdiagram") => MermaidDiagramType::Er,
            s if s.starts_with("gantt") => MermaidDiagramType::Gantt,
            s if s == "pie" || s.starts_with("pie ") => MermaidDiagramType::Pie,
            s if s.starts_with("journey") => MermaidDiagramType::Journey,
            s if s.starts_with("gitgraph") => MermaidDiagramType::GitGraph,
            s if s.starts_with("mindmap") => MermaidDiagramType::Mindmap,
            s if s.starts_with("timeline") => MermaidDiagramType::Timeline,
            s if s.starts_with("quadrantchart") => MermaidDiagramType::Quadrant,
            s if s.starts_with("requirementdiagram") => MermaidDiagramType::Requirement,
            s if s.starts_with("c4") => MermaidDiagramType::C4,
            _ => MermaidDiagramType::Unknown,
        };
    }
    MermaidDiagramType::Unknown
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_single_flowchart() {
        let md = "Some intro.\n\n```mermaid\ngraph TD\n  A --> B\n```\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Flowchart);
        assert!(blocks[0].source.contains("A --> B"));
        // Line 1: "Some intro.", 2: "", 3: ```mermaid, 4: graph TD, 5: A-->B, 6: ```
        assert_eq!(blocks[0].start_line, 3);
        assert_eq!(blocks[0].end_line, 6);
    }

    #[test]
    fn test_extract_multiple_blocks() {
        let md = "\
```mermaid
sequenceDiagram
  Alice->>Bob: Hi
```

text

```mermaid
pie
  \"A\" : 50
  \"B\" : 50
```
";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 2);
        assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Sequence);
        assert_eq!(blocks[1].diagram_type, MermaidDiagramType::Pie);
    }

    #[test]
    fn test_extract_no_mermaid() {
        let md = "```rust\nfn main() {}\n```\n\n```python\nprint(1)\n```";
        assert!(extract_mermaid_blocks(md).is_empty());
        assert!(!has_mermaid_blocks(md));
    }

    #[test]
    fn test_extract_non_mermaid_info_string_ignored() {
        // ```mermaid-custom should NOT match (longer word).
        let md = "```mermaidfoo\ngraph TD\n```\n";
        assert!(extract_mermaid_blocks(md).is_empty());
    }

    #[test]
    fn test_extract_case_insensitive_fence() {
        let md = "```Mermaid\ngraph LR\n  X --> Y\n```\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Flowchart);
    }

    #[test]
    fn test_extract_trailing_info_after_mermaid() {
        // ```mermaid {args} is valid CommonMark info string.
        let md = "```mermaid\nflowchart TD\n  A --> B\n```\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
    }

    #[test]
    fn test_extract_four_backtick_fence() {
        let md = "````mermaid\ngraph TD\n  A --> B\n````\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
        assert!(blocks[0].source.contains("A --> B"));
    }

    #[test]
    fn test_extract_unterminated_fence() {
        // An unterminated mermaid fence should not produce a block
        // (avoid swallowing the rest of the document).
        let md = "```mermaid\ngraph TD\n  A --> B\n";
        assert!(extract_mermaid_blocks(md).is_empty());
    }

    #[test]
    fn test_extract_nested_inner_fence_not_mermaid() {
        // An inner ```rust block inside a ```mermaid block — the closing
        // fence of rust is NOT the closing fence of mermaid (different info).
        // Actually in CommonMark, the first closing fence closes the block.
        // Here the inner ``` closes the mermaid block early.
        let md = "```mermaid\ngraph TD\n```\n```rust\nfn x() {}\n```\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].source, "graph TD");
    }

    #[test]
    fn test_classify_all_types() {
        let cases = [
            ("graph TD\n  A --> B", MermaidDiagramType::Flowchart),
            ("flowchart LR\n  X --> Y", MermaidDiagramType::Flowchart),
            ("sequenceDiagram\n  A->>B: m", MermaidDiagramType::Sequence),
            ("classDiagram\n  class A", MermaidDiagramType::Class),
            ("stateDiagram-v2\n  [*] --> s1", MermaidDiagramType::State),
            ("erDiagram\n  A ||--o{ B", MermaidDiagramType::Er),
            ("gantt\n  title t", MermaidDiagramType::Gantt),
            ("pie\n  \"x\" : 1", MermaidDiagramType::Pie),
            ("journey\n  title t", MermaidDiagramType::Journey),
            ("gitGraph\n  commit", MermaidDiagramType::GitGraph),
            ("mindmap\n  root", MermaidDiagramType::Mindmap),
            ("timeline\n  title t", MermaidDiagramType::Timeline),
            ("quadrantChart\n  title t", MermaidDiagramType::Quadrant),
            (
                "requirementDiagram\n  requirement r",
                MermaidDiagramType::Requirement,
            ),
            ("C4Context\n  title t", MermaidDiagramType::C4),
        ];
        for (src, expected) in &cases {
            assert_eq!(classify_diagram(src), *expected, "misclassified: {src:?}");
        }
    }

    #[test]
    fn test_classify_skips_comments_and_directives() {
        let src = "%%{init: {\"theme\": \"dark\"}}%%\n%% comment line\ngraph TD\n  A --> B";
        assert_eq!(classify_diagram(src), MermaidDiagramType::Flowchart);
    }

    #[test]
    fn test_classify_unknown_type() {
        assert_eq!(
            classify_diagram("someUnknownDiagram\n  ..."),
            MermaidDiagramType::Unknown
        );
        assert_eq!(classify_diagram(""), MermaidDiagramType::Unknown);
    }

    #[test]
    fn test_has_mermaid_blocks_short_circuits() {
        let md = "```mermaid\nflowchart\n```\n";
        assert!(has_mermaid_blocks(md));
        assert!(!has_mermaid_blocks("no code blocks here"));
    }

    #[test]
    fn test_mermaid_block_serialization() {
        let block = MermaidBlock {
            source: "graph TD\n  A --> B".to_string(),
            start_line: 5,
            end_line: 8,
            diagram_type: MermaidDiagramType::Flowchart,
        };
        let json = serde_json::to_string(&block).unwrap();
        assert!(json.contains("\"diagramType\":\"flowchart\""));
        assert!(json.contains("\"startLine\":5"));
        let parsed: MermaidBlock = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, block);
    }

    #[test]
    fn test_empty_source_block() {
        // ```mermaid immediately followed by closing fence.
        let md = "```mermaid\n```\n";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1);
        assert!(blocks[0].source.is_empty());
        assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Unknown);
    }

    // ---- Regression tests for #3726 ----

    #[test]
    fn test_mermaid_inside_wider_code_fence() {
        // A ```mermaid fence nested inside a 4-backtick documentation block is
        // literal text and must NOT be extracted (#3726).
        let md = "````\n```mermaid\ngraph TD\nA --> B\n```\n````\n";
        assert!(extract_mermaid_blocks(md).is_empty());
        assert!(!has_mermaid_blocks(md));
    }

    #[test]
    fn test_mermaid_inside_wider_fence_then_real_block() {
        // After the wrapping 4-backtick block closes, a genuine mermaid block
        // in the same document must still be found (#3726).
        let md = "\
````
```mermaid
graph TD
A --> B
```
````
text

```mermaid
flowchart LR
X --> Y
```
";
        let blocks = extract_mermaid_blocks(md);
        assert_eq!(blocks.len(), 1, "only the real (post-fence) block");
        assert_eq!(blocks[0].diagram_type, MermaidDiagramType::Flowchart);
        assert!(blocks[0].source.contains("X --> Y"));
        assert!(has_mermaid_blocks(md));
    }

    #[test]
    fn test_mermaid_inside_tilde_fence() {
        // A ```mermaid fence nested inside a ~~~ block is literal text (#3726).
        let md = "~~~\n```mermaid\ngraph TD\nA --> B\n```\n~~~\n";
        assert!(extract_mermaid_blocks(md).is_empty());
        assert!(!has_mermaid_blocks(md));
    }

    #[test]
    fn test_mermaid_inside_rust_code_fence() {
        // A ```mermaid fence nested inside a regular ```rust block is literal
        // text (#3726).
        let md = "```rust\nlet md = \"```mermaid\\ngraph TD\\n```\";\n```\n";
        assert!(extract_mermaid_blocks(md).is_empty());
        assert!(!has_mermaid_blocks(md));
    }

    #[test]
    fn test_classify_pie_keyword_not_prefix() {
        // "pie" should not match "piece", "pier", etc. (#3726 secondary).
        assert_eq!(
            classify_diagram("pie\n  \"x\" : 1"),
            MermaidDiagramType::Pie
        );
        assert_eq!(
            classify_diagram("piece of cake"),
            MermaidDiagramType::Unknown
        );
        assert_eq!(
            classify_diagram("pier reviews"),
            MermaidDiagramType::Unknown
        );
    }
}
